(require examples/native.lisp)
(defvar http-module (n-require 'http))
(defun get-keys (r) (n-call (n-get (n-global Object) 'keys) r))
(defun get-headers (r) (n-get r 'headers))
(defun get-user-agent (r) (n-get (get-headers r) 'user-agent))
(defun send. (r data) (n-call (n-get r 'send) data))
(defvar server (n-call (n-get http-module 'createServer) (n-callback (req res)
                                                                     (send. res (get-headers r)))))
