(defun random () (n-call (n-get (n-global Math) 'random)))
(defun floor () (n-call (n-get (n-global Math) 'floor)))
(defun ceil () (n-call (n-get (n-global Math) 'ceil)))
(defun log (a) (n-call (n-get (n-global 'console) 'log) a))
(defun sqrt (a) (n-call (n-get (n-global 'Math) 'sqrt) a))
(defun sin (a) (n-call (n-get (n-global 'Math) 'sin) a))
(defun cos (a) (n-call (n-get (n-global 'Math) 'cos) a))
(defun acos (a) (n-call (n-get (n-global 'Math) 'acos) a))
(defun pow (a b) (n-call (n-get (n-global 'Math) 'pow) a b))
(defvar m_pi (n-get (n-global 'Math) 'PI))
